apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-container
          image: epomatti/k8s-config-product
          ports:
            - containerPort: 80
          env:
            - name: INVENTORY_URL
              valueFrom:
                configMapKeyRef:
                  name: sys-app-product
                  key: INVENTORY_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory-container
          image: epomatti/k8s-config-inventory
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 80
